### ISSUE TITLE
npm start 'Unexpected token import'

### ISSUE THREAD

**Issue by MurhafSousli** [EyeSeeTea/user-app#10]
I am getting this error recently on `npm start`

![image](https://user-images.githubusercontent.com/8130692/30239551-aa01300c-9567-11e7-8e76-96700476a1f7.png)

Are you familiar with this error? could it be the proxy in webpack.config.js external sources while `npm start` ?

![image](https://user-images.githubusercontent.com/8130692/30239848-4ab128e0-956d-11e7-8d65-566ba0540c81.png)

**Comment by MurhafSousli** [comment]
I also tried a fresh clone, repeated the installation steps and still getting the same error

**Comment by adrianq** [comment]
Is it in d2 library? If so, can you try to git pull the latest from dataset-configuration branch in d2, npm install and npm run build-only? It looks like the code is not transpiled.... maybe double check the link is working properly. Last time we met it was working, is this due to any code change on your side?

**Comment by MurhafSousli** [comment]
@adrianq I am not sure, I tried what you suggested but it didn't make a difference.

Yea It was working, I finished the first PR, but when I started with the next task, I tried to use `Moment.js` which is already installed in our `package.json`.

DetailsComponent.js
```ts
import moment from 'moment'
  // ...
 getValueToRender(fieldName, value) {

    switch (fieldName) {
      case 'lastUpdated' | 'created':
        return <div>{moment(new Date(value).format('yyyy/MM/dd'))}</div>
     //  ....
    }
  }
```
It didn't work, and since then `npm start` is not working. I thought maybe a server is being used while compiling and it is off for some reason because even when I get a new clone it is giving the same error `Unexpected token import`

Can you check if `npm start` is working on your side?

**Comment by adrianq** [comment]
@MurhafSousli I have tested the whole thing with your branch and with a fresh new clone in development. Both of them are working for me. The only thing that I noticed is that I am getting a similar error to yours when the npm link to the d2-ui is not properly configured. In other words, if I git checkout development and run an npm install and start (without linking d2-ui) I get the same error. Can you double check your npm link is properly configured? I am aware that you probably have already checked this but just in case... Otherwise, maybe it has to do with node and npm version. Give me a shout (by mail) whenever you are around and we can have a quick chat and try to debug it together either today or tomorrow morning (I won't be at home most of the day today).

**Comment by adrianq** [comment]
@MurhafSousli any progress with this? I guess you won't be able to work until we fix this, right?

**Comment by MurhafSousli** [comment]
@adrianq I formatted my PC, got a fresh windows install. 

Now when I clone d2-ui I get this on `npm install`

![image](https://user-images.githubusercontent.com/8130692/30270183-585c1436-96f4-11e7-9ee9-13a96e3103cf.png)

**Comment by adrianq** [comment]
I am sorry to hear that you had to format your PC....

Can you try deleting the postinstall from the package.json and run it again? I was also having some problems with this line and this is a pending discussion with @tokland

**Comment by MurhafSousli** [comment]
@adrianq I needed to do it anyway :)
I tried that, `npm install` passed without errors now, but `npm run build-only` shows the same error

**Comment by adrianq** [comment]
If you try to run `babel src --out-dir lib` or `compass compile` in your command line, what do you get? Is babel properly configured in your PC?

**Comment by MurhafSousli** [comment]
babel is not recognized (I read babel should not be installed globally), `compass compile` works

**Comment by MurhafSousli** [comment]
I installed babel-cli globally, now `babel src --out-dir lib` gives the same error as `npm run build-only`
