### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#5]
- [x] Add filter by user roles
- [x] Add filter by user group
- [x] Modify search textfield to look into the rest of the columns

**Comment by tokland** [comment]
For the filters you can use material-ui select field: http://www.material-ui.com/#/components/select-field

Search: See src/List/List.component.js, key state `searchString`. The actual filtering is done at src/List/list.store.js.

**Comment by adrianq** [comment]
- [ ] Double check the api is not working for filtering
- [ ] Review PR and Merge

**Comment by tokland** [comment]
I can confirm the bug in the API. I was able to filter text+userGroup or text+userRole but text+userGroup+userRole ignored the third filter. That happens in 27/28/29. It works for dev.

Example, this returns users even correctly filtered by the text and userRole ID, but should not get results because of the WRONGID, but it does:

```
fields="id,displayName,userCredentials[userRoles],userGroups"
filters="filter=displayName:ilike:kamara&filter=userCredentials.userRoles.id:eq:TMK9CMZ2V98&filter=userGroups.id:eq:WRONGID"
curl -g -sS -u admin:district \
  "https://play.dhis2.org/android-previous2/api/users?paging=false&fields=${fields}&${filters}&rootJunction=AND" | js-beautify```
