### ISSUE TITLE
Future dates for entering targets

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-app#56]
Country offices need to enter target data yearly and for the full project period. With the DC app, they only have the current month.
For some projects they enter target data until 2021.

**Comment by tokland** [comment]
Erika is right, we effectively support only the _monthly_ period type. Although the user can select any other type, values automatically added to "data input periods" are still monthly. 

I think we discussed this and left it for future iterations since automatically creating periods for all the types is not trivial. I think we should allow only periods that we explicitly support, at least monthly (that we have) and yearly (that we should implement). We could ask Erika if there any other period they plan to use.

For the record, those are the values examples for each period type:

```
Daily: 20140101 -> 20141231
Weekly: 2014W1 -> 2014W52
Monthly: 201401 -> 201412
BiMonthly: 201401B -> 201406B
Quarterly: 2014Q1 -> 2014Q4
Sixmonthly: 2014S1, 2014S2
Sixmonthly April: 2014AprilS1, 2014AprilS2
Yearly: 2014
(Yearly) Financial April: 2015April
(Yearly) Financial July: 2015July
(Yearly) Financial Oct: 2015Oct
```

**Comment by adrianq** [comment]
@tokland This is much simpler than what we thought. If you remember the rule is to copy start and end date from the project into the data set. They claim this is not happening at the moment and the end date is usually the current date. Can you please double check with the latest dump if we have an error there? I doubt it but just in case... I even asked them if the problem is that the project was updated after creating the dataset but they said this is not the case.

**Comment by tokland** [comment]
Aaah, ok. I am not able to reproduce it, I'll ask her for an example on their servers.

Still, we should do something about the "period type" selector. For now, it'd make sense to remove it altogether since only monthly values would work.

**Comment by tokland** [comment]
As we've discussed, probably she was referring to the period selector in webentry. Asked in blessed repo.

I've checked the _openFuturePeriods_ field: when left empty it's set to 0, which makes no future months to be shown. So it seems we'll have to set a hacky arbitrary value (and hide it under the rug)

**Comment by tokland** [comment]
- [ ] Calculate and set openFuturePeriods to end of project.
